In [4]:
import torch.nn as nn
import torch

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [7]:
class CustomAttentionHeadBlock(nn.Module):

    def __init__(self,config):
        super().__init__()
        ## nn.Linear can be used to represent a matrix
        # self.Q = nn.Linear(config.n_embd, config.n_embd)
        # self.K = nn.Linear(config.n_embd, config.n_embd)
        # self.V = nn.Linear(config.n_embd, config.n_embd)
        # But I want the raw Parameter
        # we sample from 1/embedding_dimension
        self.Q = nn.Parameter(torch.randn(config.n_embd, config.n_embd)*torch.sqrt(torch.tensor(1.0/config.n_embd)))
        self.K = nn.Parameter(torch.randn(config.n_embd, config.n_embd)*torch.sqrt(torch.tensor(1.0/config.n_embd)))
        self.V = nn.Parameter(torch.randn(config.n_embd, config.n_embd)*torch.sqrt(torch.tensor(1.0/config.n_embd)))

        self.ln_1 = nn.LayerNorm(config.n_embd)
        self.ln_2 = nn.LayerNorm(config.n_embd)
        
        self.mlp = nn.Sequential(
            nn.Linear(config.n_embd, 4*config.n_embd),
            nn.GELU(),
            nn.Linear(4*config.n_embd, config.n_embd),
        )
    
    def forward(self, X):
        """ B x T x C : B=Batch, T=Sequence Length, C=Channels""" 
        """ Q : C x C, K : C x C, V : C x C """
        queries = Q @ X # B x (T
        pass

In [ ]:
position_embedding_table = 

In [12]:
torch.arange(7)

tensor([0, 1, 2, 3, 4, 5, 6])

In [8]:
""" B x T x C : B=Batch, T=Sequence Length, C=Channels""" 
""" Q : C x C, K : C x C, V : C x C """

B = 4
T = 8
C = 2

X = torch.randn(B, T, C)
print(X)

tensor([[[-0.2374, -0.4143],
         [-0.5765,  0.7790],
         [ 0.7443,  0.3480],
         [-0.3817, -0.9289],
         [ 0.5543,  0.4119],
         [ 0.5328, -0.1533],
         [ 0.0216,  0.7703],
         [ 0.3882, -0.0276]],

        [[-0.8803,  0.2467],
         [ 1.3765, -2.0477],
         [ 0.0900,  0.6292],
         [ 0.4066, -0.3066],
         [ 1.6702, -1.4386],
         [ 0.0670,  0.8862],
         [ 0.9379, -1.0628],
         [ 1.8591,  0.6913]],

        [[ 0.5470, -0.2360],
         [ 0.9461,  0.4047],
         [ 1.4713,  2.1826],
         [-0.3717, -1.2865],
         [-0.6546,  0.0807],
         [ 0.2192,  1.5398],
         [ 0.4428, -0.4590],
         [ 2.0703,  2.2711]],

        [[ 0.9144, -0.9806],
         [-1.1561,  0.4412],
         [-0.9772,  0.9412],
         [-0.0686,  0.7128],
         [-0.0818, -0.6172],
         [ 1.0673, -0.5928],
         [-0.4637,  0.0429],
         [-0.1320, -0.4210]]])


In [14]:
position_embedding_table = nn.Embedding(T, C)
print(position_embedding_table)

Embedding(8, 2)


In [20]:
position_embedding_table(torch.tensor(7))

tensor([ 0.1659, -0.1739], grad_fn=<EmbeddingBackward0>)

In [9]:
Q = torch.ones(C, C)

In [10]:
Q @ X

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [4, 2] but got: [4, 8].

In [ ]:
from dataclasses import dataclass

@dataclass
class Config:
    n_embd:int = 4

C = new CustomTransformerBlock(new Config())